### ISSUE TITLE
Checkout has expired 

### ISSUE THREAD

**Issue by ocastx** [Shopify/mobile-checkout-sdk-ios#34]
> First of all, thank you so much for this great SDK! We couldn't wait to integrate it in our mobile apps and here is the first (minor) issue we've discovered: 

When calling `present` with a checkout URL of a store that has no checkout extensibility enabled, the SDK throws an error "Checkout has expired". We tried multiple different URLs (checkout URL and cart URL) but the error was always the same. 

Finally, we switched to a new development shop where the error did not appear anymore. The difference between the stores was that one has checkout extensibility enabled and the other one not.

**Steps to reproduce**

1. Create checkout URL on store that has checkout.liquid modified
2. Call `ShopifyCheckout.present()`

**Expected behavior**

Error message which explains that Mobile Checkout SDK does not work with Shops without checkout extensibility enabled

**Actual behavior**

 Error message `checkoutExpired(message: "Checkout has expired")`

**Comment by cianBuckley** [comment]
Hi there! Thanks for being so proactive with our dev sdk! 

I see you're doing this on a 'classic' checkout. The SDK only supports shops that have migrated to the new C1 checkout. We should do a couple things here:

* Document this properly! My apologies, I don't think we have been very clear about this requirement. 
* Fail better! we do have some interception handling on 404 and 410. right now they're coupled. we will split. in event of a 404 from a classic checkout URL, I think the best approach would be to 404 on the UI side and throw a detailed stacktrace highlighting this issue to devs

**Comment by ocastx** [comment]
Hi @cianBuckley, thank you for the quick response! 

Yes, I think that is the issue we're running into generally. After creating the issue, I also noticed that we get the same error when using `checkoutCreate` instead of `cartCreate` (former being 'classic' checkout as well I guess?)

As you said, it's no immediate bug but due to missing documentation. IMO a better error message would be the first step, because then dev can quickly identify that he/she's using the 'wrong' checkout.

**Comment by kierobinson1** [comment]
Hey everyone,
Just implementing this into my app now to see how it looks, and was also getting the "Checkout has expired" error which led me here. Am I right in thinking that this SDK is only available to be used on stores that are Shopify Plus if it needs to have the new extensible checkout? Or can I enable the extensible checkout on a regular store too?

Apologies if this is a daft question but I couldn't see any way to have extensible checkout without being on Shopify Plus so thought I'd ask

**Comment by cianBuckley** [comment]
@kierobinson1 you don't need to be Shopify Plus! The shop needs to be migrated to our latest checkout platform, which supports the mobile checkout sdk regardless of license. Some stores that are still using some liquid scripts (which need to have a plus license) have yet to migrate.

I don't have enough details to know why you're getting this error. Can you tell me your setup? What steps do you take to get this error?
